### PR TITLE
update flower

### PR DESCRIPTION
**Pull request by thebestnom**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thebestnom** [comment]
@conda-forge-admin, please rerender

**Comment by kwilcox** [comment]
Did a new requirement pop up that required you to remove `noarch: python`?

**Comment by thebestnom** [comment]
there are selector, which conda forge linter told that can't work with noarch
EDIT: this is the requirment from flower github
celery>=3.1.0; python_version<"3.7"
celery>=4.3.0; python_version>="3.7"
tornado>=5.0.0,<6.0.0; python_version<"3.5.2"
tornado>=5.0.0,<7.0.0; python_version>="3.5.2"
humanize==0.5.1
pytz
futures; python_version=="2.7"
which I translated to recipe selectors

**Comment by thebestnom** [comment]
@kwilcox everything passed, mind merging?

**Comment by kwilcox** [comment]
@ocefpaf This license packaged correctly?

*edit* @thebestnom no need to include the license file here, its included in the source distribution of `flower` and referenced from the recipe.

**Comment by ocefpaf** [comment]
> @ocefpaf This license packaged correctly?
> 
> _edit_ @thebestnom no need to include the license file here, its included in the source distribution of `flower` and referenced from the recipe.

Yep. If the license file is in the source you don't need to copy it here.

**Comment by thebestnom** [comment]
Removed 👍

**Pull request merged**
